/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Webonise' at '27/5/17 1:47 PM' with Gradle 2.3
 *
 * @author Webonise, @date 27/5/17 1:47 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
